<a href="https://colab.research.google.com/github/Anushka7928/codsoft_Task/blob/main/codsoft_Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
titanic = pd.read_csv('Titanic-Dataset.csv')

titanic.shape

In [ ]:
test =pd.read_csv('Titanic-Dataset.csv')
test.shape

(891, 12)

In [ ]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
ports = pd.get_dummies(titanic.Embarked,prefix='Embarked')

In [ ]:
Titanic = Titanic.join(ports)
Titanic.drop({'Embarked'},axis = 1,inplace = true)

NameError: name 'Titanic' is not defined

In [ ]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False,False,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,False,True

In [ ]:
titanic.Sex = titanic.Sex.map({'male':0,'female':1})

In [ ]:
y = titanic.Survived.copy()
x = titanic.drop(['Survived'],axis=1)

In [ ]:
x.drop(['Cabin','Ticket','Name','PassengerId'], axis = 1, inplace = True)

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Pclass      891 non-null    int64
 1   Sex         891 non-null    int64
 2   Age         714 non-null    float64
 3   SibSp       891 non-null    int64
 4   Parch       891 non-null    int64
 5   Fare        891 non-null    float64
 6   Embarked    889 non-null    object
 7   Embarked_C  891 non-null    bool
 8   Embarked_Q  891 non-null    bool
 9   Embarked_S  891 non-null    bool
dtypes: bool(3), float64(2), int64(4), object(1)
memory usage: 51.5+ KB

In [ ]:
x.isnull().values.any()

True

In [ ]:
x[pd.isnull(x).any(axis =1)]

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Embarked_C,Embarked_Q,Embarked_S
5,3,0,NaN,0,0,8.4583,Q,False,True,False
17,2,0,NaN,0,0,13.0000,S,False,False,True
19,3,1,NaN,0,0,7.2250,C,True,False,False
26,3,0,NaN,0,0,7.2250,C,True,False,False
28,3,1,NaN,0,0,7.8792,Q,False,True,False
...,...,...,...,...,...,...,...,...,...,...
859,3,0,NaN,0,0,7.2292,C,True,False,False
863,3,1,NaN,8,2,69.5500,S,False,False,True
868,3,0,NaN,0,0,9.5000,S,False,False,True
878,3,0,NaN,0,0,7.8958,S,False,False,True
888,3,1,NaN,1,2,23.4500,S,False,False,True

In [ ]:
x.Age.fillna(x.Age.mean(),inplace = True)

<ipython-input-36-a6fbb71875b5>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x.Age.fillna(x.Age.mean(),inplace = True)

In [ ]:
x.isnull().values.any()

True

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_valid,y_train,y_valid  = train_test_split(x,y, test_size = 0.2, random_state = 7)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
model. fit(x_train,y_train)

ValueError: could not convert string to float: 'S'

In [ ]:
model.score(x_train,y_train)

ValueError: could not convert string to float: 'S'